version: '2'
services:
  zookeeper:
    container_name: istac-zookeeper
    image: confluentinc/cp-zookeeper:3.1.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    container_name: istac-kafka
    image: confluentinc/cp-kafka:3.1.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.99.100:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.99.100:9092
    depends_on:
      - zookeeper

  schema-registry:
    container_name: istac-schema-registry
    image: confluentinc/cp-schema-registry:3.1.1
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=192.168.99.100:2181
      - SCHEMA_REGISTRY_HOST_NAME=localhost
    depends_on:
      - zookeeper
      - kafka

#  kafka-rest:
#    container_name: istac-kafka-rest
#    image: confluentinc/cp-kafka-rest:3.1.1
#    ports:
#      - "8082:8082"
#    environment:
#      - KAFKA_REST_ZOOKEEPER_CONNECT=192.168.99.100:2181
#    depends_on:
#      - zookeeper
#      - kafka
#      - schema-registry
