## HOWTO
## > vagrant init ubuntu/trusty64
## > vagrant up
## To update configuration... > vagrant reload

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # see boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.network "private_network", type: "dhcp"
 
  config.vm.provision "shell", path: "bootstrap.sh"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "vagrant_istac_buscador"
  end
  
end
