package es.gobcan.istac.idxmanager.service.test.util;

import es.gobcan.istac.jaxi.pxservice.api.dominio.NucleoMetadatos;

public class MocksObjects {

    public static NucleoMetadatos crearNucleoIstac(String nombre, String codigo) {
        NucleoMetadatos nucleoIstacDomain = new NucleoMetadatos();
        nucleoIstacDomain.setIdentifierUniversal("urn:uuid:XXXXX-XXXXX-XXXXX-XXXXX-12345");
        nucleoIstacDomain.setTitle("Este es mi titulito de prueba.");
        return nucleoIstacDomain;
    }

    // public static NucleoMetadatos crearNucleoMetadatos() {
    // NucleoMetadatos nucleoMetadatos = new NucleoMetadatos();
    // nucleoMetadatos.setVersion("version");
    // nucleoMetadatos.getVersionRationaleType().add("versionRationaleType1");
    // nucleoMetadatos.getVersionRationaleType().add("versionRationaleType2");
    // nucleoMetadatos.setVersionRationale("versionRationale");
    // nucleoMetadatos.setDateVersion(new Date());
    // nucleoMetadatos.setDateNextVersion(new Date());
    // nucleoMetadatos.setVersionResponsibilityCreator("versionResponsibilityCreator");
    // nucleoMetadatos.getVersionResponsibilityContributor().add("versionResponsibilityContributor1");
    // nucleoMetadatos.getVersionResponsibilityContributor().add("versionResponsibilityContributor2");
    // nucleoMetadatos.setVersionResponsibilitySubmitted("versionResponsibilitySubmitted");
    // nucleoMetadatos.getVersionResponsibilityAccepted().add("versionResponsibilityAccepted1");
    // nucleoMetadatos.getVersionResponsibilityAccepted().add("versionResponsibilityAccepted2");
    // nucleoMetadatos.setVersionResponsibilityIssued("versionResponsibilityIssued");
    // nucleoMetadatos.setVersionResponsibilityOutofprint("versionResponsibilityOutofprint");
    // nucleoMetadatos.setProcStatus("procStatus");
    // nucleoMetadatos.setIdentifier("identifier");
    // nucleoMetadatos.setIdentifierUniversal("identifierUniversal");
    // nucleoMetadatos.setTitle("title");
    // nucleoMetadatos.getSubtitle().add("subtitle1");
    // nucleoMetadatos.getSubtitle().add("subtitle2");
    // nucleoMetadatos.getTitleAlternative().add("titleAlternative1");
    // nucleoMetadatos.getTitleAlternative().add("titleAlternative2");
    // nucleoMetadatos.setLanguage("language");
    // nucleoMetadatos.getLanguages().add("languages1");
    // nucleoMetadatos.getLanguages().add("languages2");
    // nucleoMetadatos.setSurveyTitle("surveyTitle");
    // nucleoMetadatos.setSurveyAlternative("surveyAlternative");
    // nucleoMetadatos.setSurveyCode("surveyCode");
    // nucleoMetadatos.getSubjectAreas().add("subjectAreas1");
    // nucleoMetadatos.getSubjectAreas().add("subjectAreas2");
    // nucleoMetadatos.getSubjectCodes().add("subjectCodes1");
    // nucleoMetadatos.getSubjectCodes().add("subjectCodes2");
    // nucleoMetadatos.getDescription().add("description1");
    // nucleoMetadatos.getDescription().add("description2");
    // nucleoMetadatos.getAbstract().add("abstracto1");
    // nucleoMetadatos.getAbstract().add("abstracto2");
    // nucleoMetadatos.getKeywords().add("keywords1");
    // nucleoMetadatos.getKeywords().add("keywords2");
    // nucleoMetadatos.getCoverageSpatial().add("coverageSpatial1");
    // nucleoMetadatos.getCoverageSpatial().add("coverageSpatial2");
    // nucleoMetadatos.getCoverageSpatialCodes().add("coverageSpatialCodes1");
    // nucleoMetadatos.getCoverageSpatialCodes().add("coverageSpatialCodes2");
    // nucleoMetadatos.getCoverageTemporal().add("coverageTemporal1");
    // nucleoMetadatos.getCoverageTemporal().add("coverageTemporal2");
    // nucleoMetadatos.getCoverageTemporalCodes().add("coverageTemporalCodes1");
    // nucleoMetadatos.getCoverageTemporalCodes().add("coverageTemporalCodes2");
    // nucleoMetadatos.setType("type");
    // nucleoMetadatos.getFormat().add("format1");
    // nucleoMetadatos.getFormat().add("format2");
    // nucleoMetadatos.getFormatExtent().add("formatExtent1");
    // nucleoMetadatos.getFormatExtent().add("formatExtent2");
    // nucleoMetadatos.setCreator("creator");
    // nucleoMetadatos.getContributor().add("contributor1");
    // nucleoMetadatos.getContributor().add("contributor2");
    // nucleoMetadatos.setDateCreated(new Date());
    // nucleoMetadatos.setLastUpdate(new Date());
    // nucleoMetadatos.setDateSubmitted(new Date());
    // nucleoMetadatos.setDateNextUpdate(new Date());
    // nucleoMetadatos.setUpdateFrequency("updateFrequency");
    // nucleoMetadatos.setRangeDatesValid("rangeDatesValid");
    // nucleoMetadatos.getPublisher().add("publisher1");
    // nucleoMetadatos.getPublisher().add("publisher2");
    // nucleoMetadatos.getMediator().add("mediator1");
    // nucleoMetadatos.getMediator().add("mediator2");
    // nucleoMetadatos.setDateAccepted(new Date());
    // nucleoMetadatos.setDateIssued(new Date());
    // nucleoMetadatos.setRangeDatesAvailable("rangeDatesAvailable");
    // nucleoMetadatos.getAudience().add("audience1");
    // nucleoMetadatos.getAudience().add("audience2");
    // nucleoMetadatos.getEducationLevel().add("educationLevel1");
    // nucleoMetadatos.getEducationLevel().add("educationLevel2");
    // nucleoMetadatos.getBibliographicCitation().add("bibliographicCitation1");
    // nucleoMetadatos.getBibliographicCitation().add("bibliographicCitation2");
    // nucleoMetadatos.getConformsTo().add("conformsTo1");
    // nucleoMetadatos.getConformsTo().add("conformsTo2");
    // nucleoMetadatos.getSource().add("source1");
    // nucleoMetadatos.getSource().add("source2");
    // nucleoMetadatos.setIsVersionOf("isVersionOf");
    // nucleoMetadatos.getHasVersion().add("hasVersion1");
    // nucleoMetadatos.getHasVersion().add("hasVersion2");
    // nucleoMetadatos.getReplaces().add("replaces1");
    // nucleoMetadatos.getReplaces().add("replaces2");
    // nucleoMetadatos.setIsReplacedBy("isReplacedBy1");
    // nucleoMetadatos.getRequires().add("requires1");
    // nucleoMetadatos.getRequires().add("requires2");
    // nucleoMetadatos.getIsRequiredBy().add("isRequiredBy1");
    // nucleoMetadatos.getIsRequiredBy().add("isRequiredBy2");
    // nucleoMetadatos.getHasPart().add("hasPart1");
    // nucleoMetadatos.getHasPart().add("hasPart2");
    // nucleoMetadatos.getIsPartOf().add("isPartOf1");
    // nucleoMetadatos.getIsPartOf().add("isPartOf2");
    // nucleoMetadatos.getIsReferencedBy().add("isReferencedBy1");
    // nucleoMetadatos.getIsReferencedBy().add("isReferencedBy2");
    // nucleoMetadatos.getReferences().add("references1");
    // nucleoMetadatos.getReferences().add("references2");
    // nucleoMetadatos.getIsFormatOf().add("isFormatOf1");
    // nucleoMetadatos.getIsFormatOf().add("isFormatOf2");
    // nucleoMetadatos.getHasFormat().add("hasFormat1");
    // nucleoMetadatos.getHasFormat().add("hasFormat2");
    // nucleoMetadatos.getRightsHolder().add("rightsHolder1");
    // nucleoMetadatos.getRightsHolder().add("rightsHolder2");
    // nucleoMetadatos.setDateCopyrighted(new Date());
    // nucleoMetadatos.getLicense().add("license1");
    // nucleoMetadatos.getLicense().add("license2");
    // nucleoMetadatos.setAccessRights("accessRights");
    // nucleoMetadatos.setVisitCount("visitCount");
    // nucleoMetadatos.setVisitTime("visitTime");
    // nucleoMetadatos.setVisitLastDate(new Date());
    // nucleoMetadatos.setShareCount("shareCount");
    // nucleoMetadatos.setDownloadCount("downloadCount");
    // nucleoMetadatos.setBookmarkCount("bookmarkCount");
    // nucleoMetadatos.getTags().add("tags1");
    // nucleoMetadatos.getTags().add("tags2");
    // return nucleoMetadatos;
    // }

}
