-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    


-- Create normal entities
CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL
);


    	
CREATE TABLE TB_EXTERNAL_ITEMS (
  ID BIGINT NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  CODE_NESTED VARCHAR(255),
  URI VARCHAR(4000) NOT NULL,
  URN VARCHAR(4000),
  URN_PROVIDER VARCHAR(4000),
  MANAGEMENT_APP_URL VARCHAR(4000),
  VERSION BIGINT NOT NULL,
  TITLE_FK BIGINT,
  TYPE VARCHAR(255) NOT NULL
);


    	
CREATE TABLE TB_LOCALISED_STRINGS (
  ID BIGINT NOT NULL,
  LABEL VARCHAR(4000) NOT NULL,
  LOCALE VARCHAR(255) NOT NULL,
  IS_UNMODIFIABLE BOOLEAN,
  VERSION BIGINT NOT NULL,
  INTERNATIONAL_STRING_FK BIGINT NOT NULL
);


    	
CREATE TABLE TB_RECOMMENDED_KEYWORDS (
  ID BIGINT NOT NULL,
  KEYWORD VARCHAR(255) NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  CATEGORY_FK BIGINT
);


    	
CREATE TABLE TB_RECOMMENDED_LINKS (
  ID BIGINT NOT NULL,
  URL VARCHAR(4000) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE TIMESTAMP,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  RECOMMENDED_KEYWORD BIGINT NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
		
ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

		
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

		
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

		
ALTER TABLE TB_RECOMMENDED_KEYWORDS ADD CONSTRAINT PK_TB_RECOMMENDED_KEYWORDS
	PRIMARY KEY (ID)
;

		
ALTER TABLE TB_RECOMMENDED_LINKS ADD CONSTRAINT PK_TB_RECOMMENDED_LINKS
	PRIMARY KEY (ID)
;

    

-- Unique constraints
    






-- Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_RECOMMENDED_KEYWORDS ADD CONSTRAINT FK_TB_RECOMMENDED_KEYWORDS_CATEGORY_FK
	FOREIGN KEY (CATEGORY_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  
ALTER TABLE TB_RECOMMENDED_LINKS ADD CONSTRAINT FK_TB_RECOMMENDED_LINKS_RECOMMENDED_KEYWORD
	FOREIGN KEY (RECOMMENDED_KEYWORD) REFERENCES TB_RECOMMENDED_KEYWORDS (ID)
;

  

    

-- Index


    